---
title: "BeaverNutrientAnalysis"
format: html
editor: visual
---

```{r}
#| warning: false
library(ggplot2)
library(readxl)
library(dplyr)
library(cowplot)
```

```{r}
setwd("/Users/hannahrichardson/Documents/BSU/Spring '23/Field Methods/FieldMethodsHydro")
list.files()
df <- read.csv("Quality Beaver Meadows Data Template.csv")
```

## Week 1

```{r}
#Above and below pool
date<- "2/24/23"
#Above and below pool
NOx <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = NOx_mgL, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  ylab('NOx (mg/L)')+
  ggtitle('Week 1')+
  theme(plot.title = element_text(hjust = 0.5))+
  theme_bw()

PO4 <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = PO4_mgL, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  ylab('PO4 (mg/L)')+
  theme_bw()

NH4 <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = NH4_mgL, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  ylab('NH4 (mg/L)')+
  theme_bw()

temp <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = Temp._C, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  xlab('Site Type')+
  ylab('Temp C')+
  theme_bw()

EC <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = EC, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab('Site Type')+
  ylab('EC (uS/cm)')+
  theme_bw()

Wk1<-plot_grid(NOx, PO4, NH4, temp, EC, 
                nrow =5)

```

## Week 2

```{r}
date<- "3/3/23"
#Above and below pool
NOx <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = NOx_mgL, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  ylab(NULL)+
  ggtitle('Week 2')+
  theme(plot.title = element_text(hjust = 0.5))+
  theme_bw()

PO4 <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = PO4_mgL, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  ylab(NULL)+
  theme_bw()

NH4 <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = NH4_mgL, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  ylab(NULL)+
  theme_bw()

temp <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = Temp._C, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  ylab(NULL)+
  theme_bw()

EC <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = EC, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab('Site Type')+
  ylab(NULL)+
  theme_bw()

Wk2<-plot_grid(NOx, PO4, NH4, temp, EC, 
                nrow =5)

```

## Week 3

```{r}
date<- "3/10/23"
#Above and below pool
NOx <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = NOx_mgL, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  ylab(NULL)+
  ggtitle('Week 3')+
  theme(plot.title = element_text(hjust = 0.5))+
  theme_bw()

PO4 <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = PO4_mgL, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
ylab(NULL)+
  theme_bw()

NH4 <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = NH4_mgL, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  ylab(NULL)+
  theme_bw()

temp <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = Temp._C, fill= Site_Location))+
  geom_boxplot()+
  xlab(NULL)+
ylab(NULL)+
  theme_bw()+
    theme(legend.position = c(0.35, 0.7),
        legend.background = element_rect( fill = alpha("white", 0)))+
  labs(fill = "Site Location")

EC <- df %>%
  filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = EC, fill= Site_Location))+
  geom_boxplot(show.legend=FALSE)+
  xlab('Site Type')+
  ylab(NULL)+
  theme_bw()

Wk3<-plot_grid(NOx, PO4, NH4, temp, EC, 
                nrow =5)
```

```{r}
allplot<-plot_grid(Wk1,Wk2,Wk3,
                   ncol= 3)

```

## Combined weeks

```{r}
#Above and below pool
NOx <- df %>%
  #filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = NOx_mgL, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  ylab('NOx (mg/L)')+
  theme_bw()

PO4 <- df %>%
  #filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = PO4_mgL, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  ylab('PO4 (mg/L)')+
  theme_bw()

NH4 <- df %>%
  #filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = NH4_mgL, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab(NULL)+
  ylab('NH4 (mg/L)')+
  theme_bw()

temp <- df %>%
  #filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = Temp._C, fill= Site_Location))+
  geom_boxplot()+
  xlab(NULL)+
  ylab('Temp C')+
  theme_bw()+
      theme(legend.position = c(0.15, 0.7),
      legend.background = element_rect( fill = alpha("white", 0)))+
  labs(fill = "Site Location")

EC <- df %>%
 # filter(Date == date)%>%
  ggplot(aes(x = Site_type, y = EC, fill= Site_Location))+
  geom_boxplot(show.legend = FALSE)+
  xlab('Site Type')+
  ylab('EC (uS/cm)')+
  theme_bw()

Combo<-plot_grid(NOx, PO4, NH4, temp, EC, 
                nrow =5)
```

## Save pdf

```{r}
pdf(file = "Allplots.pdf",
    width = 6,
    height = 10)

allplot
dev.off()

pdf(file = "Weekscombined.pdf",
    width = 4,
    height = 10)

Combo
dev.off()
```
